FROM oven/bun:1
WORKDIR /app

COPY package.json bun.lock tsconfig.json ./
COPY packages ./packages
COPY apps/api ./apps/api

RUN bun install
RUN touch .env

EXPOSE 9000
CMD ["bun", "run", "start:api"]
