/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomIndexRouteImport } from './routes/room.index'

const IndexLazyRouteImport = createFileRoute('/')()
const ErrorIndexLazyRouteImport = createFileRoute('/error/')()
const RoomRoomIdLazyRouteImport = createFileRoute('/room/$roomId')()
const ErrorRoomNotFoundLazyRouteImport = createFileRoute(
  '/error/room-not-found',
)()
const ErrorRoomFullLazyRouteImport = createFileRoute('/error/room-full')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ErrorIndexLazyRoute = ErrorIndexLazyRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error/index.lazy').then((d) => d.Route))
const RoomIndexRoute = RoomIndexRouteImport.update({
  id: '/room/',
  path: '/room/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdLazyRoute = RoomRoomIdLazyRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/room.$roomId.lazy').then((d) => d.Route))
const ErrorRoomNotFoundLazyRoute = ErrorRoomNotFoundLazyRouteImport.update({
  id: '/error/room-not-found',
  path: '/error/room-not-found',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/error/room-not-found.lazy').then((d) => d.Route),
)
const ErrorRoomFullLazyRoute = ErrorRoomFullLazyRouteImport.update({
  id: '/error/room-full',
  path: '/error/room-full',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/error/room-full.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/error/room-full': typeof ErrorRoomFullLazyRoute
  '/error/room-not-found': typeof ErrorRoomNotFoundLazyRoute
  '/room/$roomId': typeof RoomRoomIdLazyRoute
  '/room/': typeof RoomIndexRoute
  '/error/': typeof ErrorIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/error/room-full': typeof ErrorRoomFullLazyRoute
  '/error/room-not-found': typeof ErrorRoomNotFoundLazyRoute
  '/room/$roomId': typeof RoomRoomIdLazyRoute
  '/room': typeof RoomIndexRoute
  '/error': typeof ErrorIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/error/room-full': typeof ErrorRoomFullLazyRoute
  '/error/room-not-found': typeof ErrorRoomNotFoundLazyRoute
  '/room/$roomId': typeof RoomRoomIdLazyRoute
  '/room/': typeof RoomIndexRoute
  '/error/': typeof ErrorIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error/room-full'
    | '/error/room-not-found'
    | '/room/$roomId'
    | '/room/'
    | '/error/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error/room-full'
    | '/error/room-not-found'
    | '/room/$roomId'
    | '/room'
    | '/error'
  id:
    | '__root__'
    | '/'
    | '/error/room-full'
    | '/error/room-not-found'
    | '/room/$roomId'
    | '/room/'
    | '/error/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ErrorRoomFullLazyRoute: typeof ErrorRoomFullLazyRoute
  ErrorRoomNotFoundLazyRoute: typeof ErrorRoomNotFoundLazyRoute
  RoomRoomIdLazyRoute: typeof RoomRoomIdLazyRoute
  RoomIndexRoute: typeof RoomIndexRoute
  ErrorIndexLazyRoute: typeof ErrorIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error/'
      preLoaderRoute: typeof ErrorIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/': {
      id: '/room/'
      path: '/room'
      fullPath: '/room/'
      preLoaderRoute: typeof RoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/room-not-found': {
      id: '/error/room-not-found'
      path: '/error/room-not-found'
      fullPath: '/error/room-not-found'
      preLoaderRoute: typeof ErrorRoomNotFoundLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/room-full': {
      id: '/error/room-full'
      path: '/error/room-full'
      fullPath: '/error/room-full'
      preLoaderRoute: typeof ErrorRoomFullLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ErrorRoomFullLazyRoute: ErrorRoomFullLazyRoute,
  ErrorRoomNotFoundLazyRoute: ErrorRoomNotFoundLazyRoute,
  RoomRoomIdLazyRoute: RoomRoomIdLazyRoute,
  RoomIndexRoute: RoomIndexRoute,
  ErrorIndexLazyRoute: ErrorIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
