export const Names = [
  "Aether", "Nyx", "Orion", "Zephyr", "Atlas", "Cosmo", "Nova", "Solaris",
  "Nebula", "Galaxy", "Pulsar", "Quasar", "Supernova", "Eclipse", "Astra", "Astro",
  "Polaris", "Sirius", "Vega", "Rigel", "Betelgeuse", "Antares", "Arcturus", "Spica",
  "Altair", "Deneb", "Zodiac", "Zenith", "Nadir", "Starlight", "Horizon", "Orbit",
  "Comet", "Meteor", "Asteroid", "Solstice", "Equinox", "Helios", "Selene", "Aurora",
  "Loki", "Fenrir", "Valkyrie", "Hades", "Artemis", "Odin", "Thor", "Freya",
  "Heimdall", "Anubis", "Osiris", "Isis", "Horus", "Ra", "Thoth", "Bastet",
  "Zeus", "Athena", "Apollo", "Ares", "Aphrodite", "Hermes", "Poseidon", "Dionysus",
  "Persephone", "Janus", "Vulcan", "Minerva", "Diana", "Mars", "Neptune", "Pluto",
  "Phoenix", "Griffin", "Kraken", "Leviathan", "Wyvern", "Siren", "Chimera", "Pegasus",
  "Matrix", "Vector", "Neon", "Cipher", "Pixel", "Quantum", "Codec", "Synth",
  "Nexus", "Apex", "Vertex", "Volt", "Warp", "Proton", "Neutron", "Electron",
  "Helix", "Radar", "Chrono", "Epoch", "Zero", "Null", "Void", "Pulse",
  "Beacon", "Signal", "Frequency", "Resonance", "Amplitude", "Binary", "Digital",
  "Laser", "Sonic", "Glitch", "Byte", "Kernel", "Cyber", "Logic", "Packet", "Buffer",
  "Raven", "Draco", "Falcon", "Kitsune", "Shadow", "Blaze", "Lynx", "Viper",
  "Cobra", "Python", "Mamba", "Grizzly", "Kodiak", "Mammoth", "Raptor", "Hawk",
  "Eagle", "Osprey", "Condor", "Panther", "Leopard", "Jaguar", "Cheetah", "Puma",
  "Wolfgang", "Leon", "Zorro", "Titan", "Luna", "Terra", "Aqua", "Ignis", "Aeris",
  "Sable", "Echo", "Storm", "Kairo", "Onyx", "Rogue", "Saber", "Talon", "Gale",
  "Carbon", "Silicon", "Cobalt", "Nickel", "Copper", "Zinc", "Silver", "Gold",
  "Platinum", "Titanium", "Chrome", "Steel", "Iron", "Bronze", "Brass", "Mercury",
  "Opal", "Ruby", "Sapphire", "Emerald", "Diamond", "Amber", "Jasper", "Quartz",
  "Obsidian", "Flint", "Granite", "Basalt", "Slate", "Marble", "Clay", "Ashes",
  "Spectre", "Phantom", "Ghost", "Wraith", "Shade", "Mirage", "Illusion", "Vapor",
  "Mist", "Haze", "Frost", "Glacier", "Ice", "Avalanche", "Blizzard", "Thunder",
  "Lightning", "Cyclone", "Typhoon", "Hurricane", "Tornado", "Monsoon", "Tempest",
  "Vortex", "Maelstrom", "Abyss", "Chasm", "Canyon", "Summit", "Ridge", "Peak",
  "Plains", "Forest", "Jungle", "Desert", "Tundra", "Swamp", "Marsh", "Oasis",
  "Harbor", "Haven", "Sanctuary", "Bastion", "Citadel", "Fortress", "Outpost"
];
